export * from "./adresses.routes.js"
export * from "./auth.routes.js"
export * from "./socialProfiles.routes.js"
export * from "./user.routes.js"
export * from "./category.routes.js"
export * from "./product.routes.js"